from enum import StrEnum


class ErrorCode(StrEnum):
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_EXPIRED = "AUTH_EXPIRED"
    RATE_LIMITED = "RATE_LIMITED"
    TOKEN_REFRESH_FAILED = "TOKEN_REFRESH_FAILED"
    ACCOUNT_RISK = "ACCOUNT_RISK"
    INVALID_PARAM = "INVALID_PARAM"
    ALREADY_GREETED = "ALREADY_GREETED"
    GREET_LIMIT = "GREET_LIMIT"
    NETWORK_ERROR = "NETWORK_ERROR"
    SEARCH_ERROR = "SEARCH_ERROR"
    EVALUATE_ERROR = "EVALUATE_ERROR"
    HOOK_VETO = "HOOK_VETO"
    SKIPPED_LOW_SCORE = "SKIPPED_LOW_SCORE"
    CONFIRM_REQUIRED = "CONFIRM_REQUIRED"
    LOGIN_FAILED = "LOGIN_FAILED"
    PARSE_ERROR = "PARSE_ERROR"
    BATCH_GREET_ERROR = "BATCH_GREET_ERROR"
